name: CI-CD-Pipeline

on:
  push:
    branches: [ main ]

env:
  ACR_NAME: democicdregistry
  RG_NAME: demo-cicd-rg
  AKS_NAME: demo-aks-cluster
  IMAGE_NAME: demoapp

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install flask pytest

    - name: Run Tests
      run: |
        pytest


  terraform-deploy:

    runs-on: ubuntu-latest
    needs: build-test

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Import existing Azure resources
      run: |
        cd terraform

        terraform import azurerm_resource_group.rg \
        /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg || true

        terraform import azurerm_container_registry.acr \
        /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg/providers/Microsoft.ContainerRegistry/registries/democicdregistry || true

        terraform import azurerm_log_analytics_workspace.log \
        /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg/providers/Microsoft.OperationalInsights/workspaces/demo-aks-logs || true

        terraform import azurerm_kubernetes_cluster.aks \
        /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg/providers/Microsoft.ContainerService/managedClusters/demo-aks-cluster || true

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve


  docker-build:

    runs-on: ubuntu-latest
    needs: terraform-deploy

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    # Login to ACR
    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

    # Security Scan
    - name: Scan Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: table
        exit-code: 0

    # Push Image to ACR
    - name: Push Image
      run: |
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}


  deploy-aks:

    runs-on: ubuntu-latest
    needs: docker-build

    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    # Connect to AKS
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
        --resource-group $RG_NAME \
        --name $AKS_NAME \
        --overwrite-existing

    # Deploy Kubernetes workload

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to AKS
      run: kubectl apply -f ./k8s/deployment.yml