name: Terraform Import

on:
  workflow_dispatch:

jobs:
  import-existing-resources:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Import existing resources
        run: |
          terraform import azurerm_container_registry.acr /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg/providers/Microsoft.ContainerRegistry/registries/democicdregistry || true
          terraform import azurerm_log_analytics_workspace.log /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg/providers/Microsoft.OperationalInsights/workspaces/demo-aks-logs || true
          terraform import azurerm_kubernetes_cluster.aks /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/demo-cicd-rg/providers/Microsoft.ContainerService/managedClusters/demo-aks-cluster || true

      - name: Terraform Plan (Verify Imports)
        run: terraform plan